# Generated by Django 4.2.3 on 2023-07-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('discount', models.SmallIntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.CharField(choices=[('poshak', 'پوشاک'), ('electice', 'الکتریکی'), ('barghi', 'برقی'), ('abzar', 'ابزار')], default='poshak', max_length=200)),
                ('color', models.ManyToManyField(to='product.color', verbose_name='products')),
                ('size', models.ManyToManyField(related_name='products', to='product.size')),
            ],
        ),
    ]
